---
- name: download elsaticsearch deb file
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.10.2-amd64.deb
    dest: /tmp/elasticsearch-oss-7.10.2-amd64.deb
  tags:
    - include_elk_role

- name: install elasticsearch from deb file
  apt:
    deb: /tmp/elasticsearch-oss-7.10.2-amd64.deb
  tags:
    - include_elk_role

- name: copy elasticsearch.yml configuration
  copy:
    src: ./files/elasticsearch.yml
    dest: /etc/elasticsearch/
  tags:
    - include_elk_role
    - configure_elk

- name: start elasticsearch service
  systemd:
    daemon_reload: yes
    name: elasticsearch
    enabled: yes
    state: restarted
  tags:
    - include_elk_role
    - configure_elk

- name: get elasticsearch service status
  systemd:
    name: elasticsearch
  register: elasticsearch_service_status
  tags:
    - include_elk_role
    - configure_elk

- debug:
    var: elasticsearch_service_status.status.ActiveState
  tags:
    - include_elk_role
    - configure_elk

- name: download kibana deb file
  get_url:
    url: https://artifacts.elastic.co/downloads/kibana/kibana-oss-7.10.2-amd64.deb
    dest: /tmp/kibana-oss-7.10.2-amd64.deb
  tags:
    - include_elk_role

- name: install kibana from deb file
  apt:
    deb: /tmp/kibana-oss-7.10.2-amd64.deb
  tags:
    - include_elk_role

- name: copy kibana.yml configuration
  copy:
    src: ./files/kibana.yml
    dest: /etc/kibana/
  tags:
    - include_elk_role
    - configure_kibana

- name: start kibana service
  systemd:
    daemon_reload: yes
    name: kibana
    enabled: yes
    state: restarted
  tags:
    - include_elk_role
    - configure_kibana

- name: get kibana service status
  systemd:
    name: kibana
  register: kibana_service_status
  tags:
    - include_elk_role
    - configure_kibana

- debug:
    var: kibana_service_status.status.ActiveState
  tags:
    - include_elk_role
    - configure_kibana


- name: copy elk consul service file
  copy:
    src: ./files/elasticsearch-service.json
    dest: /etc/consul.d/
    group: consul
    owner: consul
  notify:
    - restart consul service
  tags:
    - include_elk_role


#- name: copy elasticsearch consul service file
#  copy:
#    src: ./files/elasticsearch-service.json
#    dest: /etc/consul.d/
#    group: consul
#    owner: consul
#  notify:
#    - restart consul service
#  tags:
#    - include_elk_role
#
#- name: copy kibana consul service file
#  copy:
#    src: ./files/kibana-service.json
#    dest: /etc/consul.d/
#    group: consul
#    owner: consul
#  notify:
#    - restart consul service
#  tags:
#    - include_elk_role