---
- name: download filebeat deb file
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-oss-7.11.0-amd64.deb
    dest: /tmp/filebeat-oss-7.11.0-amd64.deb
  tags:
    - install_filebeat_services

- name: install filebeat from deb file
  apt:
    deb: /tmp/filebeat-oss-7.11.0-amd64.deb
  tags:
    - install_filebeat_services

- name: keep filebeat original config yml
  command: mv /etc/filebeat/filebeat.yml /etc/filebeat/filebeat.yml.BCK

- name: copy filebeat config yml
  copy:
    src: ./files/filebeat.yml
    dest: /etc/filebeat/
  tags:
    - install_filebeat_services
    - configure_filebeat

- name: start filebeat service
  systemd:
    daemon_reload: yes
    name: filebeat
    enabled: yes
    state: restarted
  tags:
    - install_filebeat_services
    - configure_filebeat

- name: copy filebeat consul service file
  copy:
    src: ./files/filebeat-service.json
    dest: /etc/consul.d/
    group: consul
    owner: consul
  notify:
    - restart consul service
  tags:
    - include_elk_role